container:
  cpu: 1
  memory: 128Mb

lint_task:
  container:
    image: silkeh/clang:latest
  test_script: make clang-tidy

build_task:
  depends_on:
    - lint
  matrix:
    - name: clang
      env:
        CC: clang
      container:
        matrix:
          image: silkeh/clang:6
          image: silkeh/clang:7
      install_script:
        - apt update
        - apt install -y libgcc-6-dev
    - name: gcc
      env:
        CC: gcc
      container:
        matrix:
          image: gcc:6
          image: gcc:7
  test_script: make bin/nanocbor.so
